# Generated by Django 5.1 on 2024-12-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
