# Generated by Django 5.1 on 2024-12-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_alter_student_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactenquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('massege', models.CharField(max_length=200)),
            ],
        ),
    ]
